on: [push]
env:
  OPENWRT_VERSION: "21.02.2"
  ARCH: x86-64
jobs:
  Build-openwrt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod u+x build.sh
      - run: ./build.sh "$OPENWRT_VERSION" "$ARCH"
      - run: tree .
      - uses: actions/upload-artifact@v2
        with:
          name: openwrt-$OPENWRT_VERSION-$ARCH-generic-ext4-combined.img.gz
          path: openwrt-imagebuilder-$OPENWRT_VERSION-$ARCH.Linux-x86_64/bin/targets/x86/64/openwrt-$OPENWRT_VERSION-$ARCH-generic-ext4-combined.img.gz
