on: [push]
jobs:
  Build-openwrt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod u+x build.sh
      - run: ./build.sh
      - run: tree .
      - uses: actions/upload-artifact@v2
        with:
          name: openwrt-21.02.2-x86-64-generic-ext4-combined.img.gz
          path: openwrt-imagebuilder-21.02.2-x86-64.Linux-x86_64/bin/targets/x86/64/openwrt-21.02.2-x86-64-generic-ext4-combined.img.gz
